### ISSUE TITLE
change Chinese translation.

### ISSUE THREAD

**Issue by yhl452493373** [dwesterwick/SPTOpenSesame#4]
It's my bad, but to avoid duplication with the original text, it is necessary to change the translation.

Just change '打开门' to '芝麻开门' in file ch.resx.

**Comment by dwesterwick** [comment]
No problem, I'll put that update in the next release. Thanks.

**Comment by dwesterwick** [comment]
This has been fixed in the 2.1.1 release.

**Comment by yhl452493373** [comment]
thx
